#!/bin/bash

echo -e  "\033[1;34m TraceHunter-Foresic Collector \033[0m"
#  Verifica se o script está rodando como root
if [[ $EUID -ne 0 ]]; then
    echo -e "\033[1;31m Estes script precisa ser executado como root.\033[0m"
    exit  1
fi

# Criando diretório para os arquivos coletados
COLLECTED_DIR="collected_files"
mkdir -p "$COLLECTED_DIR"

# Mensagem de Início
echo -e "\033[1;35m Coletando arquivos do sistema... \033[0m"

# Coleta de Informações do Sistema
echo -e "\033[0;95m Listando informações sobre discos e partições... \033[0m"
lsblk > "$COLLECTED_DIR/disk_info.txt"

# Coleta de Conexões de Rede
echo -e "\033[0;95m Listando informações de rede... \033[0m"
ss -tunapl > "$COLLECTED_DIR/active_connections.txt"
netstat -tunapl -a > "$COLLECTED_DIR/open_ports.txt"

# Coleta de Processos
echo -e "\033[0;95m Coletando lista de processos... \033[0m"
ps -au > "$COLLECTED_DIR/process_list.txt"

# Coleta de Registros do Sistema
echo -e "\033[0;95m Coletando logs do sistema... \033[0m"
cp /var/log/syslog "$COLLECTED_DIR/syslog.log"
cp /var/log/auth.log "$COLLECTED_DIR/auth.log"
cp /var/log/dmesg "$COLLECTED_DIR/dmesg.log"

# Coleta de Arquivos de Configuração
echo -e "\033[0;95m Coletando arquivos de configuração... \033[0m"
cp -r /etc "$COLLECTED_DIR"

# Coleta de Lista de Arquivos no Diretório Raiz
echo -e "\033[0;95m Listando o diretório raíz... \033[0m"
ls -la / "$COLLECTED_DIR" > "$COLLECTED_DIR/root_dir_list.txt"

# Compactação e Nomeação do Arquivo de Saída
tar -czf "TraceHunter_{Hostname}_{DataHora}.tar.gz"
